version: 1.2
workflows:
   - name: make-fofn
     subclass: WDL
     primaryDescriptorPath: /make-fofn.wdl
     testParameterFiles:
     -  /make-fofn.input.json
   - name: generate-sample-map
     subclass: WDL
     primaryDescriptorPath: /generate-sample-map.wdl
     testParameterFiles:
     -  /generate-sample-map.input.json
   - name: copy-files-to-gs-directory 
     subclass: WDL
     primaryDescriptorPath: /copy-files-to-gs-directory.wdl
     testParameterFiles:
     -  /copy-files-to-gs-directory.input.json
